package com.android.acerem.xemgp.ui;
import android.app.*;import android.content.*;import android.database.Cursor;import android.provider.OpenableColumns;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import com.android.acerem.xemgp.auth.AuthManager;import com.android.acerem.xemgp.data.DataRepository;import com.android.acerem.xemgp.util.Ui;import java.util.concurrent.*;
public class ImportActivity extends Activity { private static final int DATA=10,ZIP=11; private Uri dataUri,zipUri; private TextView dataStatus,zipStatus,progress; private Button continueButton; private ExecutorService executor=Executors.newSingleThreadExecutor(); private int pad;
 protected void onCreate(Bundle b){super.onCreate(b);Ui.configure(this);pad=Ui.dp(this,22);Ui.applyBars(this);build();}
 private void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=Ui.column(this);root.setPadding(pad,pad,pad,pad);root.setBackgroundColor(Ui.BG);TextView eyebrow=Ui.text(this,"GIA PHẢ · OFFLINE ARCHIVE",12,Ui.ACCENT);eyebrow.setLetterSpacing(.15f);root.addView(eyebrow,new LinearLayout.LayoutParams(-1,Ui.dp(this,30)));root.addView(Ui.heading(this,"Lưu giữ những\nđiều quan trọng.",32),new LinearLayout.LayoutParams(-1,Ui.dp(this,100)));TextView sub=Ui.text(this,"Nhập dữ liệu gia phả và thư viện ảnh để bắt đầu khám phá câu chuyện của gia đình.",15,Ui.MUTED);sub.setLineSpacing(0,1.15f);root.addView(sub,new LinearLayout.LayoutParams(-1,Ui.dp(this,66)));root.addView(fileCard("📄  File dữ liệu gia phả","Bắt buộc",true),new LinearLayout.LayoutParams(-1,Ui.dp(this,112)));LinearLayout.LayoutParams zlp=new LinearLayout.LayoutParams(-1,Ui.dp(this,112));zlp.topMargin=Ui.dp(this,14);root.addView(fileCard("🖼  File ảnh gia phả","Có thể bỏ qua nếu chưa có",false),zlp);progress=Ui.text(this,"",13,Ui.ACCENT);progress.setGravity(Gravity.CENTER);root.addView(progress,new LinearLayout.LayoutParams(-1,Ui.dp(this,42)));continueButton=Ui.button(this,"Tiếp tục mở gia phả  →",true);continueButton.setOnClickListener(v->continueImport());LinearLayout.LayoutParams blp=new LinearLayout.LayoutParams(-1,Ui.dp(this,54));blp.topMargin=Ui.dp(this,10);root.addView(continueButton,blp);Button downloadButton=Ui.button(this,"Tải gia phả  →",false);downloadButton.setOnClickListener(v->openWebViewer());LinearLayout.LayoutParams dlp=new LinearLayout.LayoutParams(-1,Ui.dp(this,54));dlp.topMargin=Ui.dp(this,10);root.addView(downloadButton,dlp);TextView note=Ui.text(this,"Ảnh sẽ được lưu trong bộ nhớ riêng của ứng dụng để sử dụng offline. Không cần quyền truy cập thư viện ảnh.",12,Ui.MUTED);note.setGravity(Gravity.CENTER);note.setPadding(12,Ui.dp(this,18),12,0);root.addView(note,new LinearLayout.LayoutParams(-1,Ui.dp(this,70)));scroll.addView(root);setContentView(scroll);}
 private LinearLayout fileCard(String title,String hint,boolean required){LinearLayout card=Ui.column(this);card.setPadding(Ui.dp(this,16),Ui.dp(this,12),Ui.dp(this,12),Ui.dp(this,12));card.setBackground(Ui.outline(Ui.SURFACE,Ui.LINE,Ui.dp(this,18)));LinearLayout.LayoutParams t=new LinearLayout.LayoutParams(-1,Ui.dp(this,30));TextView h=Ui.heading(this,title,15);card.addView(h,t);LinearLayout line=Ui.row(this);TextView status=Ui.text(this,required?"Chưa chọn file .enc":"Chưa chọn file .zip",13,Ui.MUTED);line.addView(status,new LinearLayout.LayoutParams(0,Ui.dp(this,46),1));Button choose=Ui.button(this,"Chọn",false);choose.setMinHeight(Ui.dp(this,42));line.addView(choose,new LinearLayout.LayoutParams(Ui.dp(this,90),Ui.dp(this,46)));card.addView(line);TextView small=Ui.text(this,hint,11,required?Ui.COPPER:Ui.MUTED);card.addView(small,new LinearLayout.LayoutParams(-1,Ui.dp(this,18)));if(required){dataStatus=status;choose.setOnClickListener(v->pick(DATA));}else{zipStatus=status;choose.setOnClickListener(v->pick(ZIP));}return card;}
 private void pick(int kind){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(kind==DATA?"application/octet-stream":"application/zip");i.putExtra(Intent.EXTRA_MIME_TYPES,kind==DATA?new String[]{"application/octet-stream","text/plain","application/octet-stream"}:new String[]{"application/zip","application/x-zip-compressed"});startActivityForResult(i,kind);}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;Uri u=data.getData();if(u==null)return;String name=displayName(u).toLowerCase();if(request==DATA){if(!name.endsWith(".enc")){toast("Vui lòng chọn đúng file .enc.");return;}dataUri=u;dataStatus.setText("✓  "+shortName(u));dataStatus.setTextColor(Ui.ACCENT);}else{if(!name.endsWith(".zip")){toast("Vui lòng chọn đúng file .zip.");return;}zipUri=u;zipStatus.setText("✓  "+shortName(u));zipStatus.setTextColor(Ui.ACCENT);}}
 private String displayName(Uri u){try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception ignored){}return String.valueOf(u.getLastPathSegment());} private String shortName(Uri u){return displayName(u);} private void continueImport(){if(dataUri==null){toast("Hãy chọn file dữ liệu .enc trước.");return;}continueButton.setEnabled(false);progress.setText("Đang kiểm tra file gia phả…");executor.execute(()->{try{String fp=DataRepository.importData(this,dataUri);AuthManager.clearRemembered(this);if(zipUri!=null){runOnUiThread(()->progress.setText("Đang nhập ảnh…"));int count=DataRepository.extractImages(this,zipUri,fp,(done,total)->runOnUiThread(()->progress.setText("Đang nhập ảnh… "+done+" / "+total)));runOnUiThread(()->progress.setText("Đã nhập "+count+" ảnh"));}runOnUiThread(()->{startActivity(new Intent(this,LoginActivity.class));finish();});}catch(Exception e){runOnUiThread(()->{continueButton.setEnabled(true);progress.setText("");toast("File không hợp lệ hoặc không thể nhập. Dữ liệu cũ vẫn được giữ nguyên.");});}});}
 private void openWebViewer(){try{Intent browser=new Intent(Intent.ACTION_VIEW,Uri.parse("https://ace-rem.github.io/WebGiaPhaViewer/"));browser.addCategory(Intent.CATEGORY_BROWSABLE);startActivity(browser);}catch(Exception e){toast("Không tìm thấy trình duyệt để mở Web Viewer.");}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
