package com.android.acerem.xemgp.ui;

import android.app.*;import android.content.*;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import com.google.android.material.bottomsheet.BottomSheetDialog;import com.android.acerem.xemgp.auth.AuthManager;import com.android.acerem.xemgp.data.*;import com.android.acerem.xemgp.tree.*;import com.android.acerem.xemgp.util.Ui;import java.util.*;

public class ViewerActivity extends Activity implements TreeCanvasView.Listener {
 private FamilyData data;private FamilyGraph graph;private TreeCanvasView tree;private TextView contextLabel,searchSummary;private final List<Button> filterButtons=new ArrayList<>();private final List<View> overviewViews=new ArrayList<>();private Set<String> familyIds;private String selectedId;private int activeFilter=0;private boolean chartOnly;
 protected void onCreate(Bundle b){super.onCreate(b);Ui.configure(this);data=AuthManager.active();if(data==null){startActivity(new Intent(this,LoginActivity.class));finish();return;}graph=new FamilyGraph(data);familyIds=graph.familyIds();selectedId=b==null?null:b.getString("selected");chartOnly=b!=null&&b.getBoolean("chartOnly",false);Ui.applyBars(this);build();if(chartOnly)applyChartOnly();}
 private void build(){boolean landscape=getResources().getConfiguration().orientation==android.content.res.Configuration.ORIENTATION_LANDSCAPE;int headerHeight=landscape?54:70;int headerPad=landscape?5:10;LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.BG);LinearLayout header=Ui.row(this);header.setPadding(Ui.dp(this,landscape?12:18),Ui.dp(this,headerPad),Ui.dp(this,10),Ui.dp(this,landscape?4:8));LinearLayout brand=Ui.column(this);TextView small=Ui.text(this,"GIA PHẢ · FAMILY ARCHIVE",10,Ui.ACCENT);small.setLetterSpacing(.12f);brand.addView(small);brand.addView(Ui.heading(this,data.familyName,landscape?15:18));header.addView(brand,new LinearLayout.LayoutParams(0,Ui.dp(this,landscape?42:54),1));Button search=Ui.button(this,"⌕  Tìm",false);search.setMinHeight(Ui.dp(this,landscape?36:44));search.setOnClickListener(v->openSearch());header.addView(search,new LinearLayout.LayoutParams(Ui.dp(this,landscape?78:86),Ui.dp(this,landscape?38:46)));Button more=Ui.button(this,"⋮",false);more.setMinHeight(Ui.dp(this,landscape?36:44));more.setOnClickListener(v->showMenu(more));header.addView(more,new LinearLayout.LayoutParams(Ui.dp(this,landscape?44:52),Ui.dp(this,landscape?38:46)));overviewViews.add(header);root.addView(header,new LinearLayout.LayoutParams(-1,Ui.dp(this,headerHeight)));
 LinearLayout intro=Ui.column(this);intro.setPadding(Ui.dp(this,20),Ui.dp(this,8),Ui.dp(this,20),Ui.dp(this,8));intro.addView(Ui.text(this,"LƯU GIỮ NHỮNG ĐIỀU QUAN TRỌNG",10,Ui.ACCENT));intro.addView(Ui.heading(this,data.heroTitle,landscape?18:24));intro.addView(Ui.text(this,data.description.isEmpty()?"Khám phá những mối liên kết giữa các thế hệ.":data.description,landscape?11:13,Ui.MUTED));overviewViews.add(intro);root.addView(intro,new LinearLayout.LayoutParams(-1,Ui.dp(this,landscape?62:92)));
 LinearLayout stats=Ui.row(this);stats.setPadding(Ui.dp(this,18),0,Ui.dp(this,18),Ui.dp(this,8));stats.addView(stat(String.valueOf(data.members.size()),"THÀNH VIÊN"),new LinearLayout.LayoutParams(0,Ui.dp(this,landscape?46:58),1));stats.addView(stat(String.valueOf(graph.maxGeneration+1+data.generationOffset),"THẾ HỆ"),new LinearLayout.LayoutParams(0,Ui.dp(this,landscape?46:58),1));stats.addView(stat(String.valueOf(familyIds.size()),"TRONG HỌ"),new LinearLayout.LayoutParams(0,Ui.dp(this,landscape?46:58),1));overviewViews.add(stats);root.addView(stats,new LinearLayout.LayoutParams(-1,Ui.dp(this,landscape?54:66)));
 LinearLayout filter=Ui.row(this);filter.setPadding(Ui.dp(this,16),0,Ui.dp(this,16),Ui.dp(this,8));String[] labels={"Tất cả","Trong họ","Nam","Nữ","Đương tại"};for(int i=0;i<labels.length;i++){final int k=i;Button f=Ui.button(this,labels[i],i==0);filterButtons.add(f);f.setTextSize(11);f.setMinHeight(Ui.dp(this,36));f.setPadding(8,0,8,0);f.setOnClickListener(v->{activeFilter=k;applyFilter();});filter.addView(f,new LinearLayout.LayoutParams(0,Ui.dp(this,38),1));if(i<4)((LinearLayout.LayoutParams)f.getLayoutParams()).rightMargin=Ui.dp(this,5);}overviewViews.add(filter);root.addView(filter,new LinearLayout.LayoutParams(-1,Ui.dp(this,landscape?42:46)));
 FrameLayout card=new FrameLayout(this);card.setBackground(Ui.outline(Ui.SURFACE,Ui.LINE,Ui.dp(this,18)));tree=new TreeCanvasView(this);tree.setListener(this);tree.setGraph(graph);card.addView(tree,new FrameLayout.LayoutParams(-1,-1));LinearLayout toolbar=Ui.row(this);toolbar.setPadding(Ui.dp(this,10),Ui.dp(this,8),Ui.dp(this,10),Ui.dp(this,8));contextLabel=Ui.text(this,"  Toàn bộ gia phả",12,Ui.ACCENT);toolbar.addView(contextLabel,new LinearLayout.LayoutParams(0,Ui.dp(this,38),1));Button fit=Ui.button(this,"Vừa cây",false);fit.setMinHeight(Ui.dp(this,38));fit.setOnClickListener(v->tree.fit());toolbar.addView(fit,new LinearLayout.LayoutParams(Ui.dp(this,86),Ui.dp(this,38)));FrameLayout.LayoutParams tlp=new FrameLayout.LayoutParams(-1,Ui.dp(this,54),Gravity.TOP);card.addView(toolbar,tlp);LinearLayout controls=Ui.row(this);Button minus=Ui.button(this,"−",false),plus=Ui.button(this,"+",false),full=Ui.button(this,"⛶",false);minus.setMinHeight(Ui.dp(this,44));plus.setMinHeight(Ui.dp(this,44));full.setMinHeight(Ui.dp(this,44));minus.setOnClickListener(v->tree.zoom(.82f));plus.setOnClickListener(v->tree.zoom(1.22f));full.setOnClickListener(v->toggleFullscreen());controls.addView(minus,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,46)));controls.addView(plus,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,46)));controls.addView(full,new LinearLayout.LayoutParams(Ui.dp(this,52),Ui.dp(this,46)));FrameLayout.LayoutParams clp=new FrameLayout.LayoutParams(Ui.dp(this,168),Ui.dp(this,52),Gravity.BOTTOM|Gravity.END);clp.setMargins(0,0,Ui.dp(this,12),Ui.dp(this,12));card.addView(controls,clp);root.addView(card,new LinearLayout.LayoutParams(-1,0,1));searchSummary=Ui.text(this,"Kéo để di chuyển · chụm để zoom · nhấn đúp để xem hồ sơ",11,Ui.MUTED);searchSummary.setGravity(Gravity.CENTER);root.addView(searchSummary,new LinearLayout.LayoutParams(-1,Ui.dp(this,34)));setContentView(root);tree.post(()->{tree.fit();if(selectedId!=null){tree.setSelected(selectedId);tree.focusMember(selectedId);}});}
 private TextView stat(String n,String label){TextView v=Ui.text(this,n+"\n"+label,16,Ui.STRONG);v.setGravity(Gravity.CENTER);v.setBackground(Ui.outline(Ui.SURFACE,Ui.LINE,Ui.dp(this,12)));return v;}
 private static boolean isLiving(Member m){String d=m.deathDate;if(d==null)return true;d=d.trim();return d.isEmpty()||d.equalsIgnoreCase("null")||d.equalsIgnoreCase("undefined")||d.equals("-")||d.equals("—");}
 private void applyFilter(){Set<String> ids=null;if(activeFilter==1)ids=familyIds;else if(activeFilter==2||activeFilter==3||activeFilter==4){ids=new HashSet<>();for(Member m:data.members){boolean ok=activeFilter==4?isLiving(m):familyIds.contains(m.id)&&(activeFilter==2||activeFilter==3)&&(m.gender!=null)&&(activeFilter==2?m.gender.equalsIgnoreCase("male"):m.gender.equalsIgnoreCase("female"));if(ok)ids.add(m.id);}}tree.setFilterIds(ids);for(int i=0;i<filterButtons.size();i++){Button b=filterButtons.get(i);b.setTextColor(i==activeFilter?Ui.BG:Ui.TEXT);b.setBackground(i==activeFilter?Ui.bg(Ui.ACCENT,Ui.dp(this,14)):Ui.outline(Ui.RAISED,Ui.LINE,Ui.dp(this,14)));}contextLabel.setText(activeFilter==0?"  Toàn bộ gia phả":"  Bộ lọc: "+new String[]{"Tất cả","Trong họ","Nam","Nữ","Đương tại"}[activeFilter]);}
 public void onMemberSelected(Member m,boolean open){selectedId=m.id;tree.setSelected(m.id);tree.setFocusIds(null);contextLabel.setText("  "+m.fullName);if(open)showProfile(m);}
 private void openSearch(){final EditText input=new EditText(this);input.setSingleLine(true);input.setHint("Nhập tên, không dấu cũng được…");input.setTextColor(Ui.TEXT);input.setHintTextColor(Ui.MUTED);LinearLayout box=Ui.column(this);box.setPadding(Ui.dp(this,20),0,Ui.dp(this,20),0);box.addView(input,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));LinearLayout results=Ui.column(this);ScrollView scroll=new ScrollView(this);scroll.addView(results);box.addView(scroll,new LinearLayout.LayoutParams(-1,Ui.dp(this,360)));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Tìm một thành viên").setView(box).setNegativeButton("Đóng",null).create();input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){results.removeAllViews();String q=FamilyGraph.normalize(s.toString());for(Member m:data.members)if(!q.isEmpty()&&FamilyGraph.normalize(m.fullName).contains(q)){Button r=Ui.button(ViewerActivity.this,m.fullName+"  ·  "+m.lifeDates(),false);r.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);r.setOnClickListener(v->{dialog.dismiss();selectedId=m.id;tree.setSelected(m.id);tree.focusMember(m.id);contextLabel.setText("  "+m.fullName);});results.addView(r,new LinearLayout.LayoutParams(-1,Ui.dp(ViewerActivity.this,52)));}}public void afterTextChanged(Editable e){}});dialog.getWindow();dialog.show();input.requestFocus();dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);}
 private void showProfile(Member m){BottomSheetDialog sheet=new BottomSheetDialog(this);sheet.setOnShowListener(dialog->{View bottom=sheet.findViewById(com.google.android.material.R.id.design_bottom_sheet);if(bottom!=null)bottom.setBackgroundColor(Ui.SURFACE);});LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.SURFACE);root.setPadding(Ui.dp(this,22),Ui.dp(this,18),Ui.dp(this,22),Ui.dp(this,28));TextView tag=Ui.text(this,"HỒ SƠ THÀNH VIÊN",10,Ui.ACCENT);tag.setLetterSpacing(.12f);root.addView(tag);LinearLayout identity=Ui.row(this);identity.setGravity(Gravity.TOP);identity.addView(profileAvatar(m),new LinearLayout.LayoutParams(Ui.dp(this,96),Ui.dp(this,96)));LinearLayout identityText=Ui.column(this);identityText.setPadding(Ui.dp(this,14),0,0,0);identityText.addView(Ui.heading(this,m.fullName,25));identityText.addView(Ui.text(this,m.lifeDates()+"  ·  "+(m.gender.isEmpty()?"Thành viên gia đình":m.gender),13,Ui.MUTED));identity.addView(identityText,new LinearLayout.LayoutParams(0,Ui.dp(this,96),1));root.addView(identity,new LinearLayout.LayoutParams(-1,Ui.dp(this,108)));LinearLayout facts=Ui.column(this);facts.setPadding(0,Ui.dp(this,14),0,Ui.dp(this,10));String[] fs={"Nơi sinh|"+m.birthPlace,"Nghề nghiệp|"+m.occupation,"Thứ tự con|"+(m.siblingOrder>0?String.valueOf(m.siblingOrder):"Chưa rõ"),"Ghi chú|"+m.note};for(String f:fs){String[] a=f.split("\\|",2);if(a.length>1&&!a[1].trim().isEmpty()){TextView x=Ui.text(this,a[0]+"\n"+a[1],13,Ui.TEXT);x.setPadding(0,6,0,6);facts.addView(x);}}root.addView(facts);addRelations(root,"Cha / mẹ",parents(m),sheet);addRelations(root,"Vợ / chồng",m.spouseIds,sheet);addRelations(root,"Anh / chị / em",new ArrayList<>(graph.siblings.getOrDefault(m.id,Collections.emptySet())),sheet);addRelations(root,"Con cái",graph.children.getOrDefault(m.id,Collections.emptyList()),sheet);ScrollView scroll=new ScrollView(this);scroll.addView(root);sheet.setContentView(scroll);sheet.show();}
 private View profileAvatar(Member m){FrameLayout frame=new FrameLayout(this);frame.setBackground(Ui.outline(Ui.ACCENT_SOFT,Ui.LINE,Ui.dp(this,18)));Bitmap image=loadMemberBitmap(m);if(image!=null){ImageView view=new ImageView(this);view.setImageBitmap(image);view.setScaleType(ImageView.ScaleType.CENTER_CROP);frame.addView(view,new FrameLayout.LayoutParams(-1,-1));}else{TextView initials=Ui.text(this,initials(m.fullName),25,Ui.ACCENT);initials.setGravity(Gravity.CENTER);frame.addView(initials,new FrameLayout.LayoutParams(-1,-1));}return frame;}
 private Bitmap loadMemberBitmap(Member m){String filename=FamilyGraph.imageFilename(m);if(filename==null)return null;String stem=filename.lastIndexOf(".")>0?filename.substring(0,filename.lastIndexOf(".")):filename;String[] candidates={filename,stem+".jpg",stem+".jpeg",stem+".png"};String fp=DataRepository.currentFingerprint(this);if(fp==null)return null;for(String candidate:candidates){java.io.File f=DataRepository.imageFile(this,fp,candidate);if(!f.isFile())continue;BitmapFactory.Options o=new BitmapFactory.Options();o.inPreferredConfig=Bitmap.Config.RGB_565;Bitmap b=BitmapFactory.decodeFile(f.getAbsolutePath(),o);if(b!=null)return b;}return null;}
 private static String initials(String name){String[] parts=name.trim().split("\\s+");String result="";for(int i=Math.max(0,parts.length-2);i<parts.length;i++)if(!parts[i].isEmpty())result+=parts[i].substring(0,1).toUpperCase(Locale.ROOT);return result.isEmpty()?"?":result;}
 private List<String> parents(Member m){List<String> out=new ArrayList<>();if(m.fatherId!=null)out.add(m.fatherId);if(m.motherId!=null)out.add(m.motherId);return out;}
 private void addRelations(LinearLayout root,String title,List<String> ids,BottomSheetDialog sheet){List<String> valid=new ArrayList<>();for(String id:ids)if(graph.byId.containsKey(id))valid.add(id);if(valid.isEmpty())return;root.addView(Ui.heading(this,title,14));for(String id:valid){Member r=graph.byId.get(id);Button b=Ui.button(this,"→  "+r.fullName,false);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->{sheet.dismiss();selectedId=r.id;tree.setSelected(r.id);tree.focusMember(r.id);contextLabel.setText("  "+r.fullName);});root.addView(b,new LinearLayout.LayoutParams(-1,Ui.dp(this,48)));}}
 private void showMenu(View anchor){PopupMenu menu=new PopupMenu(this,anchor);menu.getMenu().add("Giao diện "+(Ui.isDark(this)?"sáng":"tối"));android.view.SubMenu colors=menu.getMenu().addSubMenu("Chủ đề màu");String[] keys={"blue","red","yellow","green","orange"};String[] names={"Xanh dương","Đỏ","Vàng","Xanh lá cây","Cam"};for(int i=0;i<keys.length;i++)colors.add(0,i+100,i,names[i]+(Ui.palette(this).equals(keys[i])?"  ✓":""));menu.getMenu().add("Thông tin gia phả");menu.getMenu().add("Tải gia phả");menu.getMenu().add("Giới thiệu");menu.getMenu().add("Đăng xuất");menu.setOnMenuItemClickListener(item->{String title=item.getTitle().toString();if(title.equals("Tải gia phả")){openWebViewer();}else if(title.startsWith("Giao diện")){Ui.setTheme(this,Ui.palette(this),!Ui.isDark(this));recreate();}else if(item.getItemId()>=100&&item.getItemId()<105){Ui.setTheme(this,keys[item.getItemId()-100],Ui.isDark(this));recreate();}else if(title.equals("Chủ đề màu")){return true;}else if(title.equals("Giới thiệu")){showAbout();}else if(title.equals("Đăng xuất")){AuthManager.clearActive();AuthManager.clearRemembered(this);startActivity(new Intent(this,LoginActivity.class));finish();}else new AlertDialog.Builder(this).setTitle(data.familyName).setMessage(data.members.size()+" thành viên · " +(graph.maxGeneration+1+data.generationOffset)+" thế hệ\nDữ liệu được lưu và đọc hoàn toàn offline.").setPositiveButton("Đóng",null).show();return true;});menu.show();}
 private void applyChartOnly(){for(View v:overviewViews)v.setVisibility(chartOnly?View.GONE:View.VISIBLE);if(searchSummary!=null)searchSummary.setVisibility(chartOnly?View.GONE:View.VISIBLE);tree.post(tree::fit);}
 private void showAbout(){new AlertDialog.Builder(this).setTitle("Giới thiệu").setMessage("Nhà phát triển: Ace Rem\nPhiên bản: 1.0\nNgày phát hành: 29/09/2026").setPositiveButton("Đóng",null).show();}
 private void openWebViewer(){try{Intent browser=new Intent(Intent.ACTION_VIEW,Uri.parse("https://ace-rem.github.io/WebGiaPhaViewer/"));browser.addCategory(Intent.CATEGORY_BROWSABLE);startActivity(browser);}catch(Exception e){Toast.makeText(this,"Không tìm thấy trình duyệt để mở Web Viewer.",Toast.LENGTH_LONG).show();}}
 private void toggleFullscreen(){chartOnly=!chartOnly;applyChartOnly();}
 protected void onSaveInstanceState(Bundle out){out.putString("selected",selectedId);out.putBoolean("chartOnly",chartOnly);super.onSaveInstanceState(out);}
 @Override public void onBackPressed(){if(chartOnly){chartOnly=false;applyChartOnly();return;}super.onBackPressed();}
}

