package com.android.acerem.xemgp.tree;

import android.content.Context;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import androidx.annotation.Nullable;import com.android.acerem.xemgp.data.*;import java.io.File;import java.util.*;

/** Hardware-accelerated native canvas for pan/zoom/tap/double-tap tree interaction. */
public final class TreeCanvasView extends View {
    public interface Listener { void onMemberSelected(Member member, boolean openProfile); }
    private FamilyGraph graph; private Listener listener; private float scale=1f,tx=0,ty=0; private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG); private final Paint text=new Paint(Paint.ANTI_ALIAS_FLAG); private final GestureDetector gesture; private final ScaleGestureDetector pinch; private String selected; private Set<String> focusIds,filterIds; private final Map<String,Bitmap> bitmaps=new LinkedHashMap<String,Bitmap>(32,.75f,true){protected boolean removeEldestEntry(Map.Entry<String,Bitmap> e){return size()>32;}}; private float lastX,lastY;
    private int bg=Color.rgb(32,43,38),surface=Color.rgb(38,51,45),textColor=Color.rgb(251,250,243),muted=Color.rgb(162,170,160),accent=Color.rgb(167,197,163),line=Color.rgb(91,121,103),copper=Color.rgb(228,33,33);
    public TreeCanvasView(Context c){super(c);setFocusable(true); gesture=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){public boolean onDown(MotionEvent e){lastX=e.getX();lastY=e.getY();return true;}public boolean onDoubleTap(MotionEvent e){String id=hit(e.getX(),e.getY());if(id!=null&&listener!=null)listener.onMemberSelected(graph.byId.get(id),true);return true;}public boolean onSingleTapConfirmed(MotionEvent e){String id=hit(e.getX(),e.getY());if(id!=null&&listener!=null)listener.onMemberSelected(graph.byId.get(id),false);return true;}public boolean onScroll(MotionEvent e1,MotionEvent e2,float dx,float dy){tx-=dx;ty-=dy;invalidate();return true;}public boolean onFling(MotionEvent a,MotionEvent b,float vx,float vy){return true;}}); pinch=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){float old=scale;scale=Math.max(.25f,Math.min(2.8f,scale*d.getScaleFactor()));float fx=d.getFocusX(),fy=d.getFocusY();tx=fx-(fx-tx)*(scale/old);ty=fy-(fy-ty)*(scale/old);invalidate();return true;}});}
    public void setListener(Listener l){listener=l;} public void setGraph(FamilyGraph g){graph=g;fit();} public void setSelected(String id){selected=id;invalidate();} public void setFocusIds(Set<String> ids){focusIds=ids;invalidate();} public void setFilterIds(Set<String> ids){filterIds=ids;invalidate();} public void zoom(float factor){float cx=getWidth()/2f,cy=getHeight()/2f,old=scale;scale=Math.max(.25f,Math.min(2.8f,scale*factor));tx=cx-(cx-tx)*(scale/old);ty=cy-(cy-ty)*(scale/old);invalidate();} public void fit(){if(graph==null||getWidth()==0||getHeight()==0)return;float sx=(getWidth()-32f)/Math.max(graph.width,1),sy=(getHeight()-32f)/Math.max(graph.height,1);scale=Math.max(.25f,Math.min(1f,Math.min(sx,sy)));tx=(getWidth()-graph.width*scale)/2f;ty=(getHeight()-graph.height*scale)/2f;invalidate();} public void focusMember(String id){FamilyGraph.Node n=graph==null?null:graph.nodes.get(id);if(n==null)return;scale=Math.max(scale,.72f);tx=getWidth()/2f-(n.cx()*scale);ty=getHeight()/2f-(n.cy()*scale);selected=id;invalidate();}
    public void focusGeneration(int gen){if(graph==null)return;float sum=0;int count=0;for(FamilyGraph.Node n:graph.nodes.values())if(n.generation==gen){sum+=n.cx();count++;}if(count>0){scale=Math.max(scale,.55f);tx=getWidth()/2f-(sum/count*scale);ty=getHeight()/2f-((FamilyGraph.OUTER+gen*(FamilyGraph.CARD_H+FamilyGraph.ROW_GAP)+FamilyGraph.CARD_H/2f)*scale);invalidate();}}
    protected void onSizeChanged(int w,int h,int ow,int oh){if(graph!=null&&w>0&&h>0)post(this::fit);}
    protected void onDraw(Canvas canvas){bg=com.android.acerem.xemgp.util.Ui.BG;surface=com.android.acerem.xemgp.util.Ui.SURFACE;textColor=com.android.acerem.xemgp.util.Ui.STRONG;muted=com.android.acerem.xemgp.util.Ui.MUTED;accent=com.android.acerem.xemgp.util.Ui.ACCENT;line=com.android.acerem.xemgp.util.Ui.LINE;copper=com.android.acerem.xemgp.util.Ui.COPPER;super.onDraw(canvas);canvas.drawColor(bg);if(graph==null)return;canvas.save();canvas.translate(tx,ty);canvas.scale(scale,scale);drawEdges(canvas);for(FamilyGraph.Node node:graph.nodes.values())drawNode(canvas,node);canvas.restore();}
    private void drawEdges(Canvas c){paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(2.2f);for(FamilyGraph.Edge e:graph.edges){FamilyGraph.Node a=graph.nodes.get(e.from),b=graph.nodes.get(e.to);if(a==null||b==null)continue;if(filterIds!=null&&(!filterIds.contains(e.from)||!filterIds.contains(e.to)))continue;boolean dim=!matches(e.from)&&!matches(e.to);paint.setColor(e.type.equals("spouse")?Color.rgb(198,145,105):e.type.equals("sibling")?Color.rgb(126,164,145):line);paint.setAlpha(dim?45:210);Path p=new Path();if(e.type.equals("parent")){float mid=a.y+FamilyGraph.CARD_H+36;p.moveTo(a.cx(),a.y+FamilyGraph.CARD_H);p.lineTo(a.cx(),mid);p.lineTo(b.cx(),mid);p.lineTo(b.cx(),b.y);}else{p.moveTo(a.cx(),a.cy());p.lineTo(b.cx(),b.cy());}c.drawPath(p,paint);}paint.setAlpha(255);}
    private void drawNode(Canvas c,FamilyGraph.Node n){if(filterIds!=null&&!filterIds.contains(n.member.id))return;boolean dim=(focusIds!=null&&!focusIds.contains(n.member.id))||(filterIds!=null&&!filterIds.contains(n.member.id));boolean isSelected=n.member.id.equals(selected);float alpha=dim?65:255;paint.setStyle(Paint.Style.FILL);paint.setColor(surface);paint.setAlpha((int)alpha);c.drawRoundRect(n.x,n.y,n.x+FamilyGraph.CARD_W,n.y+FamilyGraph.CARD_H,16,16,paint);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(isSelected?3:1);paint.setColor(isSelected?accent:Color.rgb(72,91,80));c.drawRoundRect(n.x,n.y,n.x+FamilyGraph.CARD_W,n.y+FamilyGraph.CARD_H,16,16,paint);paint.setAlpha((int)alpha);paint.setStyle(Paint.Style.FILL);paint.setColor(hasDeathDate(n.member)?copper:Color.rgb(126,193,81));c.drawCircle(n.x+187,n.y+95,3,paint);String fn=FamilyGraph.imageFilename(n.member);Bitmap portrait=null;if(fn!=null)portrait=loadBitmap(fn);paint.setColor(portrait==null?com.android.acerem.xemgp.util.Ui.ACCENT_SOFT:Color.rgb(69,91,80));c.drawCircle(n.x+30,n.y+31,21,paint);if(portrait!=null)c.drawBitmap(portrait,null,new RectF(n.x+9,n.y+10,n.x+51,n.y+52),paint);text.setTypeface(Typeface.create("sans",Typeface.BOLD));text.setTextSize(12);text.setColor(textColor);text.setAlpha((int)alpha);String[] words=n.member.fullName.trim().split("\\s+");String line1=n.member.fullName;String line2="";if(line1.length()>22&&words.length>2){int pivot=words.length/2;line1=join(words,0,pivot);line2=join(words,pivot,words.length);}if(portrait==null){text.setColor(accent);c.drawText(initials(n.member.fullName),n.x+20,n.y+35,text);}c.drawText(line1,n.x+64,n.y+31,text);if(!line2.isEmpty())c.drawText(line2,n.x+64,n.y+46,text);text.setTypeface(Typeface.create("sans",Typeface.NORMAL));text.setTextSize(10);text.setColor(muted);c.drawText(n.member.lifeDates(),n.x+64,n.y+(line2.isEmpty()?51:65),text);String role=n.member.occupation==null||n.member.occupation.isEmpty()?(n.member.gender.equalsIgnoreCase("female")?"Thành viên nữ":"Thành viên gia đình"):n.member.occupation;if(role.length()>23)role=role.substring(0,22)+"…";c.drawText(role,n.x+64,n.y+(line2.isEmpty()?70:85),text);if(n.member.siblingOrder>0){paint.setColor(accent);paint.setAlpha((int)alpha);c.drawCircle(n.x+186,n.y+18,9,paint);text.setColor(bg);text.setTextSize(9);text.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(String.valueOf(n.member.siblingOrder),n.x+183,n.y+21,text);}paint.setAlpha(255);}
    private static boolean hasDeathDate(Member member){String date=member.deathDate;return date!=null&&!date.trim().isEmpty()&&!"null".equalsIgnoreCase(date.trim());}
    private Bitmap loadBitmap(String fn){if(fn==null)return null;if(bitmaps.containsKey(fn))return bitmaps.get(fn);String stem=fn.lastIndexOf(".")>0?fn.substring(0,fn.lastIndexOf(".")):fn;String[] candidates={fn,stem+".jpg",stem+".jpeg",stem+".png"};String fp=DataRepository.currentFingerprint(getContext());if(fp==null)return null;for(String candidate:candidates){File f=DataRepository.imageFile(getContext(),fp,candidate);if(!f.isFile())continue;BitmapFactory.Options o=new BitmapFactory.Options();o.inPreferredConfig=Bitmap.Config.RGB_565;Bitmap b=BitmapFactory.decodeFile(f.getAbsolutePath(),o);if(b!=null){bitmaps.put(fn,b);return b;}}return null;}
    private boolean matches(String id){return (focusIds==null||focusIds.contains(id))&&(filterIds==null||filterIds.contains(id));} private String hit(float sx,float sy){if(graph==null)return null;float x=(sx-tx)/scale,y=(sy-ty)/scale;for(FamilyGraph.Node n:graph.nodes.values())if(x>=n.x&&x<=n.x+FamilyGraph.CARD_W&&y>=n.y&&y<=n.y+FamilyGraph.CARD_H)return n.member.id;return null;}
    public boolean onTouchEvent(MotionEvent e){pinch.onTouchEvent(e);gesture.onTouchEvent(e);return true;} private static String initials(String n){String[] p=n.trim().split("\\s+");String s="";for(int i=Math.max(0,p.length-2);i<p.length;i++)s+=p[i].substring(0,1).toUpperCase(Locale.ROOT);return s.isEmpty()?"?":s;}private static String join(String[] a,int from,int to){StringBuilder s=new StringBuilder();for(int i=from;i<to;i++){if(s.length()>0)s.append(' ');s.append(a[i]);}return s.toString();}
}
